openapi: 3.0.2
info:
  contact:
    email: ethvalera@gmail.com
    name: Elisabeth Valera
  description: |
    Document Analyzer is an application that tracks and analyzes text documents uploaded by users.
    The application provides functionality to register, update, retrieve and delete users and teams. 
    It also provides the following functionality:
    - Counts users registered before a given period who did not upload documents during that period.
    - Calculates word frequencies for specific documents.
    - Suggests synonyms for the longest word in a text document.
  title: Document Analyzer
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /teams:
    get:
      summary: List all teams
      operationId: getAllTeams
      tags:
        - Teams
      responses:
        200:
          description: A list of all teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/team"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/internalServerError"

components:
  schemas:
    team:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Healthcare
      required:
        - id
        - name
      example:
        id: 1
        name: "Healthcare"

    internalServerError:
      type: object
      properties:
        status:
          type: integer
          example: 500
          description: The HTTP status code
        message:
          type: string
          example: "An unexpected error occurred"
          description: An error message
      required:
        - status
        - message
      example:
        status: 500
        message: "An unexpected error occurred"

